///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
/// 通过Json格式转换来的类,不能打点访问了, 需要通过方括号[]
///
class IntexLoginBean {
/*
{
  "userId": "a306e5d6-0ba8-4c6d-853e-d43370c18600",
  "userName": "glorizz",
  "emailAddress": "glorizz@sina.com",
  "phoneNumber": " 861881749667",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySWQiOiJhMzA2ZTVkNi0wYmE4LTRjNmQtODUzZS1kNDMzNzBjMTg2MDAiLCJVc2VyTmFtZSI6Imdsb3JpenoiLCJFbWFpbEFkcmVzcyI6Imdsb3JpenpAc2luYS5jb20iLCJQaG9uZU51bWJlciI6IiA4NjE4ODE3NDk2NjciLCJVc2VyUm9sZUlkIjoiMiIsIlVzZXJSb2xlIjoiQ29tbW9uVXNlciIsIm5iZiI6MTU5NTk5MjY3NiwiZXhwIjoxNTk2NDI0Njc2LCJpYXQiOjE1OTU5OTI2NzZ9.De1Tb3BBd4O9vMpc_h1uRYaavEKKjnRonA87xApP9jI",
  "refreshToken": "LFLh9Bvd/LT6fuynMBkmbAqzwmok8NOrd1H3vdzqdaRz0XYJlk9ynYQ4i74YrugI5LE7q8eMny7QxzhPn3M9eAPIZSamV7+P"
}
*/

  String userId;
  String userName;
  String emailAddress;
  String phoneNumber;
  String token;
  String refreshToken;

  IntexLoginBean({
    this.userId,
    this.userName,
    this.emailAddress,
    this.phoneNumber,
    this.token,
    this.refreshToken,
  });
  IntexLoginBean.fromJson(Map<String, dynamic> json) {
    userId = json["userId"]?.toString();
    userName = json["userName"]?.toString();
    emailAddress = json["emailAddress"]?.toString();
    phoneNumber = json["phoneNumber"]?.toString();
    token = json["token"]?.toString();
    refreshToken = json["refreshToken"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["userId"] = userId;
    data["userName"] = userName;
    data["emailAddress"] = emailAddress;
    data["phoneNumber"] = phoneNumber;
    data["token"] = token;
    data["refreshToken"] = refreshToken;
    return data;
  }
}
